manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.1.0
      import:
        name-allowlist:
          - cmsis
          - hal_nordic
    - name: tflite-micro
      remote: zephyrproject-rtos
      path: modules/ftlite-micro
      revision: 8d404de73acf7687831e16d88e86e4f73cfddf8e
